<a name="block_grid"></a>

<div class="row">
	<div class="large-12 columns">
		<h3>Block grid</h3>

		<p>Block grids are ideal for blocked-in content generated by an application, as they <b>do not require rows</b> or even numbers of elements to display correctly. If you use the <code>small-block-grid-#</code> only, the grid will keep its spacing and configuration no matter the screen size. If you use <code>large-block-grid-#</code> only, the list items will stack down progressively on top of eachother for small devices. If you use both of those classes combined, you can control the configuration and layout separately for each breakpoint.</p>

		Using only <code>small-block-grid-3</code>
		<ul class="small-block-grid-3">
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/1.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/2.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/3.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/4.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/5.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/6.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/7.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/8.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/9.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/10.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/11.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/12.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/13.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/14.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/15.jpg" /></li>
		</ul>

		Using only the <code>large-block-grid-4</code> (stack for small devices)
		<ul class="large-block-grid-4">
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/1.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/2.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/3.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/4.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/5.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/6.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/7.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/8.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/9.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/10.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/11.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/12.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/13.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/14.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/15.jpg" /></li>
		</ul>

		Using both block grids together for different layouts
		<ul class="small-block-grid-2 large-block-grid-4">
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/1.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/2.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/3.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/4.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/5.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/6.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/7.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/8.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/9.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/10.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/11.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/12.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/13.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/14.jpg" /></li>
			<li><img alt="" src="<?= ASSETS ?>/images/liquids/small/15.jpg" /></li>
		</ul>
	</div>
</div>
