<div id="foundation-icons-demo">
	<span class="general foundicon-settings" title="general foundicon-settings">&nbsp;</span>
	<span class="general foundicon-heart" title="general foundicon-heart">&nbsp;</span>
	<span class="general foundicon-star" title="general foundicon-star">&nbsp;</span>
	<span class="general foundicon-plus" title="general foundicon-plus">&nbsp;</span>
	<span class="general foundicon-minus" title="general foundicon-minus">&nbsp;</span>
	<span class="general foundicon-checkmark" title="general foundicon-checkmark">&nbsp;</span>
	<span class="general foundicon-remove" title="general foundicon-remove">&nbsp;</span>
	<span class="general foundicon-mail" title="general foundicon-mail">&nbsp;</span>
	<span class="general foundicon-calendar" title="general foundicon-calendar">&nbsp;</span>
	<span class="general foundicon-page" title="general foundicon-page">&nbsp;</span>
	<span class="general foundicon-tools" title="general foundicon-tools">&nbsp;</span>
	<span class="general foundicon-globe" title="general foundicon-globe">&nbsp;</span>
	<span class="general foundicon-home" title="general foundicon-home">&nbsp;</span>
	<span class="general foundicon-quote" title="general foundicon-quote">&nbsp;</span>
	<span class="general foundicon-people" title="general foundicon-people">&nbsp;</span>
	<span class="general foundicon-monitor" title="general foundicon-monitor">&nbsp;</span>
	<span class="general foundicon-laptop" title="general foundicon-laptop">&nbsp;</span>
	<span class="general foundicon-phone" title="general foundicon-phone">&nbsp;</span>
	<span class="general foundicon-cloud" title="general foundicon-cloud">&nbsp;</span>
	<span class="general foundicon-error" title="general foundicon-error">&nbsp;</span>
	<span class="general foundicon-right-arrow" title="general foundicon-right-arrow">&nbsp;</span>
	<span class="general foundicon-left-arrow" title="general foundicon-left-arrow">&nbsp;</span>
	<span class="general foundicon-up-arrow" title="general foundicon-up-arrow">&nbsp;</span>
	<span class="general foundicon-down-arrow" title="general foundicon-down-arrow">&nbsp;</span>
	<span class="general foundicon-trash" title="general foundicon-trash">&nbsp;</span>
	<span class="general foundicon-add-doc" title="general foundicon-add-doc">&nbsp;</span>
	<span class="general foundicon-edit" title="general foundicon-edit">&nbsp;</span>
	<span class="general foundicon-lock" title="general foundicon-lock">&nbsp;</span>
	<span class="general foundicon-unlock" title="general foundicon-unlock">&nbsp;</span>
	<span class="general foundicon-refresh" title="general foundicon-refresh">&nbsp;</span>
	<span class="general foundicon-paper-clip" title="general foundicon-paper-clip">&nbsp;</span>
	<span class="general foundicon-video" title="general foundicon-video">&nbsp;</span>
	<span class="general foundicon-photo" title="general foundicon-photo">&nbsp;</span>
	<span class="general foundicon-graph" title="general foundicon-graph">&nbsp;</span>
	<span class="general foundicon-idea" title="general foundicon-idea">&nbsp;</span>
	<span class="general foundicon-mic" title="general foundicon-mic">&nbsp;</span>
	<span class="general foundicon-cart" title="general foundicon-cart">&nbsp;</span>
	<span class="general foundicon-address-book" title="general foundicon-address-book">&nbsp;</span>
	<span class="general foundicon-compass" title="general foundicon-compass">&nbsp;</span>
	<span class="general foundicon-flag" title="general foundicon-flag">&nbsp;</span>
	<span class="general foundicon-location" title="general foundicon-location">&nbsp;</span>
	<span class="general foundicon-clock" title="general foundicon-clock">&nbsp;</span>
	<span class="general foundicon-folder" title="general foundicon-folder">&nbsp;</span>
	<span class="general foundicon-inbox" title="general foundicon-inbox">&nbsp;</span>
	<span class="general foundicon-website" title="general foundicon-website">&nbsp;</span>
	<span class="general foundicon-smiley" title="general foundicon-smiley">&nbsp;</span>
	<span class="general foundicon-search" title="general foundicon-search">&nbsp;</span>

	<hr/>

	<span class="enclosed foundicon-settings" title="enclosed foundicon-settings">&nbsp;</span>
	<span class="enclosed foundicon-heart" title="enclosed foundicon-heart">&nbsp;</span>
	<span class="enclosed foundicon-star" title="enclosed foundicon-star">&nbsp;</span>
	<span class="enclosed foundicon-plus" title="enclosed foundicon-plus">&nbsp;</span>
	<span class="enclosed foundicon-minus" title="enclosed foundicon-minus">&nbsp;</span>
	<span class="enclosed foundicon-checkmark" title="enclosed foundicon-checkmark">&nbsp;</span>
	<span class="enclosed foundicon-remove" title="enclosed foundicon-remove">&nbsp;</span>
	<span class="enclosed foundicon-mail" title="enclosed foundicon-mail">&nbsp;</span>
	<span class="enclosed foundicon-calendar" title="enclosed foundicon-calendar">&nbsp;</span>
	<span class="enclosed foundicon-page" title="enclosed foundicon-page">&nbsp;</span>
	<span class="enclosed foundicon-tools" title="enclosed foundicon-tools">&nbsp;</span>
	<span class="enclosed foundicon-globe" title="enclosed foundicon-globe">&nbsp;</span>
	<span class="enclosed foundicon-home" title="enclosed foundicon-home">&nbsp;</span>
	<span class="enclosed foundicon-quote" title="enclosed foundicon-quote">&nbsp;</span>
	<span class="enclosed foundicon-people" title="enclosed foundicon-people">&nbsp;</span>
	<span class="enclosed foundicon-monitor" title="enclosed foundicon-monitor">&nbsp;</span>
	<span class="enclosed foundicon-laptop" title="enclosed foundicon-laptop">&nbsp;</span>
	<span class="enclosed foundicon-phone" title="enclosed foundicon-phone">&nbsp;</span>
	<span class="enclosed foundicon-cloud" title="enclosed foundicon-cloud">&nbsp;</span>
	<span class="enclosed foundicon-error" title="enclosed foundicon-error">&nbsp;</span>
	<span class="enclosed foundicon-right-arrow" title="enclosed foundicon-right-arrow">&nbsp;</span>
	<span class="enclosed foundicon-left-arrow" title="enclosed foundicon-left-arrow">&nbsp;</span>
	<span class="enclosed foundicon-up-arrow" title="enclosed foundicon-up-arrow">&nbsp;</span>
	<span class="enclosed foundicon-down-arrow" title="enclosed foundicon-down-arrow">&nbsp;</span>
	<span class="enclosed foundicon-trash" title="enclosed foundicon-trash">&nbsp;</span>
	<span class="enclosed foundicon-add-doc" title="enclosed foundicon-add-doc">&nbsp;</span>
	<span class="enclosed foundicon-edit" title="enclosed foundicon-edit">&nbsp;</span>
	<span class="enclosed foundicon-lock" title="enclosed foundicon-lock">&nbsp;</span>
	<span class="enclosed foundicon-unlock" title="enclosed foundicon-unlock">&nbsp;</span>
	<span class="enclosed foundicon-refresh" title="enclosed foundicon-refresh">&nbsp;</span>
	<span class="enclosed foundicon-paper-clip" title="enclosed foundicon-paper-clip">&nbsp;</span>
	<span class="enclosed foundicon-video" title="enclosed foundicon-video">&nbsp;</span>
	<span class="enclosed foundicon-photo" title="enclosed foundicon-photo">&nbsp;</span>
	<span class="enclosed foundicon-graph" title="enclosed foundicon-graph">&nbsp;</span>
	<span class="enclosed foundicon-idea" title="enclosed foundicon-idea">&nbsp;</span>
	<span class="enclosed foundicon-mic" title="enclosed foundicon-mic">&nbsp;</span>
	<span class="enclosed foundicon-cart" title="enclosed foundicon-cart">&nbsp;</span>
	<span class="enclosed foundicon-address-book" title="enclosed foundicon-address-book">&nbsp;</span>
	<span class="enclosed foundicon-compass" title="enclosed foundicon-compass">&nbsp;</span>
	<span class="enclosed foundicon-flag" title="enclosed foundicon-flag">&nbsp;</span>
	<span class="enclosed foundicon-location" title="enclosed foundicon-location">&nbsp;</span>
	<span class="enclosed foundicon-clock" title="enclosed foundicon-clock">&nbsp;</span>
	<span class="enclosed foundicon-folder" title="enclosed foundicon-folder">&nbsp;</span>
	<span class="enclosed foundicon-inbox" title="enclosed foundicon-inbox">&nbsp;</span>
	<span class="enclosed foundicon-website" title="enclosed foundicon-website">&nbsp;</span>
	<span class="enclosed foundicon-smiley" title="enclosed foundicon-smiley">&nbsp;</span>
	<span class="enclosed foundicon-search" title="enclosed foundicon-search">&nbsp;</span>

	<hr/>

	<span class="social foundicon-thumb-up" title="social foundicon-thumb-up">&nbsp;</span>
	<span class="social foundicon-thumb-down" title="social foundicon-thumb-down">&nbsp;</span>
	<span class="social foundicon-rss" title="social foundicon-rss">&nbsp;</span>
	<span class="social foundicon-facebook" title="social foundicon-facebook">&nbsp;</span>
	<span class="social foundicon-twitter" title="social foundicon-twitter">&nbsp;</span>
	<span class="social foundicon-pinterest" title="social foundicon-pinterest">&nbsp;</span>
	<span class="social foundicon-github" title="social foundicon-github">&nbsp;</span>
	<span class="social foundicon-path" title="social foundicon-path">&nbsp;</span>
	<span class="social foundicon-linkedin" title="social foundicon-linkedin">&nbsp;</span>
	<span class="social foundicon-dribbble" title="social foundicon-dribbble">&nbsp;</span>
	<span class="social foundicon-stumble-upon" title="social foundicon-stumble-upon">&nbsp;</span>
	<span class="social foundicon-behance" title="social foundicon-behance">&nbsp;</span>
	<span class="social foundicon-reddit" title="social foundicon-reddit">&nbsp;</span>
	<span class="social foundicon-google-plus" title="social foundicon-google-plus">&nbsp;</span>
	<span class="social foundicon-youtube" title="social foundicon-youtube">&nbsp;</span>
	<span class="social foundicon-vimeo" title="social foundicon-vimeo">&nbsp;</span>
	<span class="social foundicon-flickr" title="social foundicon-flickr">&nbsp;</span>
	<span class="social foundicon-slideshare" title="social foundicon-slideshare">&nbsp;</span>
	<span class="social foundicon-picassa" title="social foundicon-picassa">&nbsp;</span>
	<span class="social foundicon-skype" title="social foundicon-skype">&nbsp;</span>
	<span class="social foundicon-steam" title="social foundicon-steam">&nbsp;</span>
	<span class="social foundicon-instagram" title="social foundicon-instagram">&nbsp;</span>
	<span class="social foundicon-foursquare" title="social foundicon-foursquare">&nbsp;</span>
	<span class="social foundicon-delicious" title="social foundicon-delicious">&nbsp;</span>
	<span class="social foundicon-chat" title="social foundicon-chat">&nbsp;</span>
	<span class="social foundicon-torso" title="social foundicon-torso">&nbsp;</span>
	<span class="social foundicon-tumblr" title="social foundicon-tumblr">&nbsp;</span>
	<span class="social foundicon-video-chat" title="social foundicon-video-chat">&nbsp;</span>
	<span class="social foundicon-digg" title="social foundicon-digg">&nbsp;</span>
	<span class="social foundicon-wordpress" title="social foundicon-wordpress">&nbsp;</span>

	<hr/>

	<span class="accessibility foundicon-wheelchair" title="accessibility foundicon-wheelchair">&nbsp;</span>
	<span class="accessibility foundicon-speaker" title="accessibility foundicon-speaker">&nbsp;</span>
	<span class="accessibility foundicon-fontsize" title="accessibility foundicon-fontsize">&nbsp;</span>
	<span class="accessibility foundicon-eject" title="accessibility foundicon-eject">&nbsp;</span>
	<span class="accessibility foundicon-view-mode" title="accessibility foundicon-view-mode">&nbsp;</span>
	<span class="accessibility foundicon-eyeball" title="accessibility foundicon-eyeball">&nbsp;</span>
	<span class="accessibility foundicon-asl" title="accessibility foundicon-asl">&nbsp;</span>
	<span class="accessibility foundicon-person" title="accessibility foundicon-person">&nbsp;</span>
	<span class="accessibility foundicon-question" title="accessibility foundicon-question">&nbsp;</span>
	<span class="accessibility foundicon-adult" title="accessibility foundicon-adult">&nbsp;</span>
	<span class="accessibility foundicon-child" title="accessibility foundicon-child">&nbsp;</span>
	<span class="accessibility foundicon-glasses" title="accessibility foundicon-glasses">&nbsp;</span>
	<span class="accessibility foundicon-cc" title="accessibility foundicon-cc">&nbsp;</span>
	<span class="accessibility foundicon-blind" title="accessibility foundicon-blind">&nbsp;</span>
	<span class="accessibility foundicon-braille" title="accessibility foundicon-braille">&nbsp;</span>
	<span class="accessibility foundicon-iphone-home" title="accessibility foundicon-iphone-home">&nbsp;</span>
	<span class="accessibility foundicon-w3c" title="accessibility foundicon-w3c">&nbsp;</span>
	<span class="accessibility foundicon-css" title="accessibility foundicon-css">&nbsp;</span>
	<span class="accessibility foundicon-key" title="accessibility foundicon-key">&nbsp;</span>
	<span class="accessibility foundicon-hearing-impaired" title="accessibility foundicon-hearing-impaired">&nbsp;</span>
	<span class="accessibility foundicon-male" title="accessibility foundicon-male">&nbsp;</span>
	<span class="accessibility foundicon-female" title="accessibility foundicon-female">&nbsp;</span>
	<span class="accessibility foundicon-network" title="accessibility foundicon-network">&nbsp;</span>
	<span class="accessibility foundicon-guidedog" title="accessibility foundicon-guidedog">&nbsp;</span>
	<span class="accessibility foundicon-universal-access" title="accessibility foundicon-universal-access">&nbsp;</span>
	<span class="accessibility foundicon-elevator" title="accessibility foundicon-elevator">&nbsp;</span>
</div>
